spring.application.name=knowledge-repository

# Spring .ENV
spring.config.import=optional:file:.env[.properties]

# Spring Database Config
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5434}/${POSTGRES_DB:knowledge-repository-db}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring JPA Config
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Security User
spring.security.user.name=${SPRING_USER:admin}
spring.security.user.password=${SPRING_PASSWORD:admin123}

# Spring Docker Compose
spring.docker.compose.enabled=false

# Liquibase Config
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Spring JWT Token Config
app.security.jwt.secret=${JWT_SECRET:2vA7f8SSWLeMBfHgsDMTNKZfDYZjLN2T79stiMrNuWe3XMZhHQSg1j6uncfXgznfJQJkKskaQWYQgiRrkMIXKR}
app.security.jwt.expiration=${JWT_EXPIRATION:24}

# Spring MVC
spring.mvc.problemdetails.enabled=true
# Pagination
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

# File upload / storage
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB
app.storage.location=${STORAGE_LOCATION:./uploads}
